### ISSUE TITLE
absolute trash

### ISSUE THREAD

**Issue by Dosado-S** [Soeeb/Movie-Rater#1]
Use 
### **PICKLE** 
lol

**Comment by Dosado-S** [comment]
pickle was easier to implement

**Comment by Dosado-S** [comment]
@marknzl

**Comment by marknzl** [comment]
@W-y0u-T

**Comment by Soeeb** [comment]
Hi! Currently I don't use pickle as it is outdated and does not work well for larger data sets. By using a database I can future proof the program as well as being able to manually remove and change entries.
