### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by marknzl** [Soeeb/Movie-Rater#2]
imma do some sick sql injection on ur website fam

**Comment by Soeeb** [comment]
Hi! I will be reporting you to the Fbi.

**Comment by marknzl** [comment]
no, please don't; i give u tip. move ur class definition into a separate file as well as all ur mysql business logic, it will look very clean and much wow. now pls don't call FBI on me <3

**Comment by Soeeb** [comment]
No, ur mum
